apiVersion: v1
kind: Pod
metadata:
  name: debian-privileged
spec:
  containers:
    - name: debian-privileged
      image: lbacik/debian-tech
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 31; done"]
      securityContext:
          privileged: true
  hostPID: true
