apiVersion: v1
kind: Pod
metadata:
  name: debian-multi
spec:
  containers:
    - name: debian-01
      image: lbacik/debian-tech
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 40; done"]
    - name: debian-02
      image: lbacik/debian-tech
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 45; done"]
    - name: debian-03
      image: debian
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 50; done"]
